# Copyright (c) OpenMMLab. All rights reserved.
from .contrastive_bbox_head import ContrastiveBBoxHead
from .cosine_sim_bbox_head import CosineSimBBoxHead
from .meta_bbox_head import MetaBBoxHead
from .multi_relation_bbox_head import MultiRelationBBoxHead
from .two_branch_bbox_head import TwoBranchBBoxHead
from .bbox_head_semantic import BBoxSemanticHead
from .convfc_bbox_semantic_head import ConvFCSemanticBBoxHead
from .convfc_bbox_head2 import ConvFCBBoxHead2, Shared2FCBBoxHead2
from .bbox_head2 import BBoxHead2
from .bbox_head_suzsd_get_bbox_without_softmax import BBoxHead_suzsd_get_bbox_without_softmax
from .convfc_bbox_head_with_unit_transfer import ConvFCBBoxHead_with_unit_transfer,  Shared2FCBBoxHead_with_unit_transfer, Shared4Conv1FCBBoxHead_with_unit_transfer
from .convfc_bbox_head_with_unit_transfer_only_vis import ConvFCBBoxHead_with_unit_transfer_only_vis,  Shared2FCBBoxHead_with_unit_transfer_only_vis, Shared4Conv1FCBBoxHead_with_unit_transfer_only_vis
from .convfc_bbox_head_with_unit_transfer_only_sem import ConvFCBBoxHead_with_unit_transfer_only_sem,  Shared2FCBBoxHead_with_unit_transfer_only_sem, Shared4Conv1FCBBoxHead_with_unit_transfer_only_sem
from .convfc_bbox_head_with_unit_transfer_plus_reg import ConvFCBBoxHead_with_unit_transfer_plus_reg,  Shared2FCBBoxHead_with_unit_transfer_plus_reg, Shared4Conv1FCBBoxHead_with_unit_transfer_plus_reg
from .convfc_bbox_head_with_unit_transfer_add_ft import ConvFCBBoxHead_with_unit_transfer_add_ft,  Shared2FCBBoxHead_with_unit_transfer_add_ft, Shared4Conv1FCBBoxHead_with_unit_transfer_add_ft
from .convfc_bbox_head_with_dpif import ConvFCBBoxHead_with_dpif, Shared2FCBBoxHead_with_dpif, Shared4Conv1FCBBoxHead_with_dpif
from .convfc_bbox_head_with_dpif_add_asso_loss import ConvFCBBoxHead_with_dpif_add_asso_loss, Shared2FCBBoxHead_with_dpif_add_asso_loss, Shared4Conv1FCBBoxHead_with_dpif_add_asso_loss
from .convfc_bbox_head_with_dpif_add_asso_loss_inference_fusion import ConvFCBBoxHead_with_dpif_add_asso_loss_inference_fusion, Shared2FCBBoxHead_with_dpif_add_asso_loss_inference_fusion, Shared4Conv1FCBBoxHead_with_dpif_add_asso_loss_inference_fusion
from .convfc_bbox_head_visual_info_transfer_direct_logits import ConvFCBBoxHead_visual_info_transfer_direct_logits, Shared2FCBBoxHead_visual_info_transfer_direct_logits, Shared4Conv1FCBBoxHead_visual_info_transfer_direct_logits
from .convfc_bbox_head_visual_info_transfer_attention_generator import ConvFCBBoxHead_visual_info_transfer_attention_generator, Shared2FCBBoxHead_visual_info_transfer_attention_generator, Shared4Conv1FCBBoxHead_visual_info_transfer_attention_generator
from .bbox_head_visual_info_transfer_attention_generator import BBoxHead_visual_info_transfer_attention_generator
from .convfc_bbox_head_visual_info_transfer_finetune_det_classifier import ConvFCBBoxHead_visual_info_transfer_finetune_det_classifier, Shared2FCBBoxHead_visual_info_transfer_finetune_det_classifier, Shared4Conv1FCBBoxHead_visual_info_transfer_finetune_det_classifier
from .convfc_bbox_head_visual_info_transfer_direct_probabilities import ConvFCBBoxHead_visual_info_transfer_direct_probabilities, Shared2FCBBoxHead_visual_info_transfer_direct_probabilities, Shared4Conv1FCBBoxHead_visual_info_transfer_direct_probabilities
from .convfc_bbox_head_visual_info_transfer_individual_softmax import ConvFCBBoxHead_visual_info_transfer_individual_softmax, Shared2FCBBoxHead_visual_info_transfer_individual_softmax, Shared4Conv1FCBBoxHead_visual_info_transfer_individual_softmax
from .convfc_bbox_head_visual_info_transfer_finetune_det_classifier_add_base import ConvFCBBoxHead_visual_info_transfer_finetune_det_classifier_add_base, Shared2FCBBoxHead_visual_info_transfer_finetune_det_classifier_add_base, Shared4Conv1FCBBoxHead_visual_info_transfer_finetune_det_classifier_add_base
from .convfc_bbox_head_visual_info_transfer_coco_65_15_1shot_finetune_det_classifier import ConvFCBBoxHead_visual_info_transfer_coco_65_15_1shot_finetune_det_classifier, Shared2FCBBoxHead_visual_info_transfer_coco_65_15_1shot_finetune_det_classifier, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_65_15_1shot_finetune_det_classifier
from .convfc_bbox_head_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd import ConvFCBBoxHead_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd, Shared2FCBBoxHead_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd
from .convfc_bbox_head_visual_info_transfer_coco_65_15_2shot_finetune_det_classifier import ConvFCBBoxHead_visual_info_transfer_coco_65_15_2shot_finetune_det_classifier, Shared2FCBBoxHead_visual_info_transfer_coco_65_15_2shot_finetune_det_classifier, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_65_15_2shot_finetune_det_classifier
from .convfc_bbox_head_visual_info_transfer_coco_65_15_3shot_finetune_det_classifier import ConvFCBBoxHead_visual_info_transfer_coco_65_15_3shot_finetune_det_classifier, Shared2FCBBoxHead_visual_info_transfer_coco_65_15_3shot_finetune_det_classifier, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_65_15_3shot_finetune_det_classifier
from .convfc_bbox_head_visual_info_transfer_coco_65_15_5shot_finetune_det_classifier import ConvFCBBoxHead_visual_info_transfer_coco_65_15_5shot_finetune_det_classifier, Shared2FCBBoxHead_visual_info_transfer_coco_65_15_5shot_finetune_det_classifier, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_65_15_5shot_finetune_det_classifier
from .convfc_bbox_head_visual_info_transfer_coco_65_15_10shot_finetune_det_classifier import ConvFCBBoxHead_visual_info_transfer_coco_65_15_10shot_finetune_det_classifier, Shared2FCBBoxHead_visual_info_transfer_coco_65_15_10shot_finetune_det_classifier, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_65_15_10shot_finetune_det_classifier
from .cosine_sim_bbox_head_visual_info_transfer_coco_65_15_1shot_finetune_det_classifier import CosineSimBBoxHead_visual_info_transfer_coco_65_15_1shot_finetune_det_classifier 
from .cosine_sim_bbox_head_visual_info_transfer_coco_65_15_2shot_finetune_det_classifier import CosineSimBBoxHead_visual_info_transfer_coco_65_15_2shot_finetune_det_classifier 
from .cosine_sim_bbox_head_visual_info_transfer_coco_65_15_3shot_finetune_det_classifier import CosineSimBBoxHead_visual_info_transfer_coco_65_15_3shot_finetune_det_classifier 
from .cosine_sim_bbox_head_visual_info_transfer_coco_65_15_5shot_finetune_det_classifier import CosineSimBBoxHead_visual_info_transfer_coco_65_15_5shot_finetune_det_classifier 
from .cosine_sim_bbox_head_visual_info_transfer_coco_65_15_10shot_finetune_det_classifier import CosineSimBBoxHead_visual_info_transfer_coco_65_15_10shot_finetune_det_classifier 
from .convfc_bbox_head_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd import ConvFCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd, Shared2FCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd
from .convfc_bbox_head_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_qwen import ConvFCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_qwen, Shared2FCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_qwen, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_qwen
from .convfc_bbox_head_visual_info_transfer_coco_73_7_10shot_two_softmax_from_suzsd import ConvFCBBoxHead_visual_info_transfer_coco_73_7_10shot_two_softmax_from_suzsd, Shared2FCBBoxHead_visual_info_transfer_coco_73_7_10shot_two_softmax_from_suzsd, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_73_7_10shot_two_softmax_from_suzsd
from .convfc_bbox_head_visual_info_transfer_coco_73_15_10shot_two_softmax_from_suzsd import ConvFCBBoxHead_visual_info_transfer_coco_73_15_10shot_two_softmax_from_suzsd, Shared2FCBBoxHead_visual_info_transfer_coco_73_15_10shot_two_softmax_from_suzsd, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_73_15_10shot_two_softmax_from_suzsd
from .convfc_bbox_head_visual_info_transfer_coco_73_80_10shot_two_softmax_from_suzsd import ConvFCBBoxHead_visual_info_transfer_coco_73_80_10shot_two_softmax_from_suzsd, Shared2FCBBoxHead_visual_info_transfer_coco_73_80_10shot_two_softmax_from_suzsd, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_73_80_10shot_two_softmax_from_suzsd
from .convfc_bbox_head_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd_65_80 import ConvFCBBoxHead_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd_65_80, Shared2FCBBoxHead_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd_65_80, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd_65_80
from .convfc_bbox_head_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd_65_80_qwen import ConvFCBBoxHead_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd_65_80_qwen, Shared2FCBBoxHead_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd_65_80_qwen, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_65_15_1shot_two_softmax_from_suzsd_65_80_qwen
from .convfc_bbox_head_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_48_65 import ConvFCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_48_65, Shared2FCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_48_65, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_48_65
from .convfc_bbox_head_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_48_65_qwen import ConvFCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_48_65_qwen, Shared2FCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_48_65_qwen, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_48_17_0shot_two_softmax_from_suzsd_48_65_qwen
from .cosine_sim_bbox_head_visual_info_transfer_voc_15_5_3shot_finetune_det_classifier import CosineSimBBoxHead_visual_info_transfer_voc_15_5_3shot_finetune_det_classifier
from .cosine_sim_bbox_head_visual_info_transfer_voc_15_5_5shot_finetune_det_classifier import CosineSimBBoxHead_visual_info_transfer_voc_15_5_5shot_finetune_det_classifier
from .cosine_sim_bbox_head_visual_info_transfer_voc_15_5_3shot_finetune_det_classifier_fsce import CosineSimBBoxHead_visual_info_transfer_voc_15_5_3shot_finetune_det_classifier_fsce
from .cosine_sim_bbox_head_visual_info_transfer_voc_15_5_5shot_finetune_det_classifier_fsce import CosineSimBBoxHead_visual_info_transfer_voc_15_5_5shot_finetune_det_classifier_fsce
from .contrastive_bbox_head_visual_info_transfer_voc_15_5_3shot_finetune_det_classifier_fsce_add_cpe import ContrastiveBBoxHead_visual_info_transfer_voc_15_5_3shot_finetune_det_classifier_fsce_add_cpe
from .contrastive_bbox_head_visual_info_transfer_voc_15_5_5shot_finetune_det_classifier_fsce_add_cpe import ContrastiveBBoxHead_visual_info_transfer_voc_15_5_5shot_finetune_det_classifier_fsce_add_cpe
from .convfc_bbox_head_visual_info_transfer_coco_60_20_10shot_finetune_det_classifier import ConvFCBBoxHead_visual_info_transfer_coco_60_20_10shot_finetune_det_classifier, Shared2FCBBoxHead_visual_info_transfer_coco_60_20_10shot_finetune_det_classifier, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_60_20_10shot_finetune_det_classifier
from .convfc_bbox_head_visual_info_transfer_coco_60_20_30shot_finetune_det_classifier import ConvFCBBoxHead_visual_info_transfer_coco_60_20_30shot_finetune_det_classifier, Shared2FCBBoxHead_visual_info_transfer_coco_60_20_30shot_finetune_det_classifier, Shared4Conv1FCBBoxHead_visual_info_transfer_coco_60_20_30shot_finetune_det_classifier
from .cosine_sim_bbox_head_visual_info_transfer_coco_60_20_10shot_fsce_finetune_det_classifier import CosineSimBBoxHead_visual_info_transfer_coco_60_20_10shot_fsce_finetune_det_classifier
from .cosine_sim_bbox_head_visual_info_transfer_coco_60_20_30shot_fsce_finetune_det_classifier import CosineSimBBoxHead_visual_info_transfer_coco_60_20_30shot_fsce_finetune_det_classifier
__all__ = [
    'CosineSimBBoxHead', 'ContrastiveBBoxHead', 'MultiRelationBBoxHead',
    'MetaBBoxHead', 'TwoBranchBBoxHead',
    'BBoxSemanticHead',
    'ConvFCSemanticBBoxHead'
    'ConvFCBBoxHead2', 'Shared2FCBBoxHead2', 'BBoxHead2'
    'ConvFCBBoxHead_with_unit_transfer',
    'Shared2FCBBoxHead_with_unit_transfer', 
    'Shared4Conv1FCBBoxHead_with_unit_transfer'
]
